### ISSUE TITLE
Compatibility with TypeScript 5.7 (array buffers)

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [uhyo/better-typescript-lib#53]
Disclaimer: TypeScript 5.7 was only just released and I'm not trying to rush you.

TypeScript 5.7 includes some [changes to how array buffers are typed](https://devblogs.microsoft.com/typescript/announcing-typescript-5-7/#typedarrays-are-now-generic-over-arraybufferlike), and it appears that better-typescript-lib will need to be updated to be compatible with it.

With TypeScript 5.7.2 and `better-typescript-lib` 2.9.0 and compiling the following file:
```ts
import * as zlib from 'node:zlib'

const result = zlib.gzipSync("test");

console.log(result.byteLength);
```

I get this error:
```
src/test.ts:5:20 - error TS2339: Property 'byteLength' does not exist on type 'Buffer<ArrayBufferLike>'.
```

Without `better-typescript-lib` there's no error.

[reproduction repository](https://github.com/ehoogeveen-medweb/better-typescript-lib-test)

**Comment by uhyo** [comment]
Yes, I need to work on TS 5.7 support. Thank you for a reminder 🙂 

Installing `better-typescript-lib` 2.9.0 essentially keeps you on TS 5.6's type definitions despite actually using TS 5.7.

 I believe `@types/node` now utilizes `typesVersions` to provide different definitions for TS <= 5.6 and 5.7, which  is problematic in this case.

Sorry for inconvenience until I release a new version. :bow:

**Comment by uhyo** [comment]
@ehoogeveen-medweb I just released a new version of better-typescript-lib which should be TS 5.7 compatible. Please try 🙂

**Comment by ehoogeveen-medweb** [comment]
Everything is working with 2.10.0 and TS 5.7, thanks!
